# Generated by Django 3.2.23 on 2024-10-12 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='nearest_station',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
