# Generated by Django 3.2.23 on 2025-02-06 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='station_latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='profile',
            name='station_longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
