# Generated by Django 3.2.23 on 2025-03-31 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20250206_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='station_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='station_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
